### ISSUE TITLE
Possibility to add image on QR

### ISSUE THREAD

**Issue by cgiupponi** [lara-zeus/qr#29]
Are you planning to add the possibility to merge an image like a logo with the qrcode?

**Comment by atmonshi** [comment]
is is in my todo list for a while now, but didnt got a chance.
I did test it as you can see [here](https://github.com/lara-zeus/qr/blob/22692db76e9312f90d2aeee318192d8d5c66efb2/src/Facades/Qr.php#L256)

we need to add support for image source by uploading or passed to the plugin or passed to the component.
will see if its possible to do so during the next week.

**Comment by yughoz** [comment]
any update ?

**Comment by atmonshi** [comment]
Done, please test and let me know
https://github.com/user-attachments/assets/10eec3b2-f5a5-4e2f-a6dd-fceb3c4ca28f

**Comment by yughoz** [comment]
<img width="1294" alt="image" src="https://github.com/user-attachments/assets/67615f0e-3094-469f-b05b-0871a869e39a">

Call to a member function getPathName() on string


after save qr-option and edit again error 
my field 
{"size":"300","type":"png","margin":"1","color":"rgba(74, 74, 74, 1)","back_color":"rgba(252, 252, 252, 1)","style":"square","hasGradient":false,"gradient_form":"rgb(69, 179, 157)","gradient_to":"rgb(241, 148, 138)","gradient_type":"vertical","hasEyeColor":false,"eye_color_inner":"rgb(241, 148, 138)","eye_color_outer":"rgb(69, 179, 157)","eye_style":"square","logo":"01J8MBW3SAEGDBEJ44ZNWYVK0S.jpg"}

**Comment by cgiupponi** [comment]
Same for me, looks like that the image is not handled after the save.

reset(): Argument #1 ($array) must be of type array, string given
![Screenshot 2024-12-11 alle 10 49 49](https://github.com/user-attachments/assets/5587cd0d-1224-491f-8ede-064e89f1c640)


EDIT:  
the error should be this, it expect some array but the logo is returned as a string: https://github.com/lara-zeus/qr/blob/a848e7cdff58a307417ddaacc3dc69cb159c91a3/src/Facades/Qr.php#L267

**Comment by atmonshi** [comment]
sorry for the delay.

@yughoz  
fixed on the last release 

@cgiupponi not sure about this error, can you test on last version and test. if still an issue please feel free to open an new one, since its diff than this issue.
