### ISSUE TITLE
PHP version support for this program

### ISSUE THREAD

**Issue by T1anjiu** [lara-zeus/qr#31]
I was try to set up the same qrcode site on my server,but i meet a problem.The docs said we need to install Laravel,so what is the Laravel version is.That I can choose what PHP version Laravel is based on its version.(Although I am aware that using the latest version of Laravel would likely ensure support, I prefer to work with the minimum required version. This has always been my approach, perhaps it's a personal quirk.)   ：）

**Comment by atmonshi** [comment]
hi, I really recommend you use the last version.

all my packages works with laravel 11 or 10, and filament 3.
and both can run on php ^8.2

**Comment by T1anjiu** [comment]
Haha, it's just a little hobby of mine, and it's not something that can't be corrected.It's just that the old php version works smoothly.I know that the new version of php is better in security and performance.😁
