### ISSUE TITLE
Error: Call to a member function getPathName() on string when open QR code has icon

### ISSUE THREAD

**Issue by maytham553** [lara-zeus/qr#39]
1. **Steps to Reproduce**:

   1. Assign an icon to the QR code.
   2. Save the configuration.
   3. Refresh the page.
   4. Open the QR code again.

2. **Observed Behavior**:

   ```
   Error: Call to a member function getPathName() on string
   ```

3. **Environment Details**: Provide information about your development setup, including:

   - **PHP Version**: 8.3.13
   - **Laravel Version**: 11.9
   - **Plugin Version**: 1.1
   - **Operating System**: macOS Sonoma 14.5

**Comment by Asmo999** [comment]
i have same issue,if you fixed it please tell me how

**Comment by atmonshi** [comment]
sorry for the delay.

should be fixed on the last release
https://github.com/lara-zeus/qr/releases/tag/1.1.17

feel free to reopen if needed.
