### ISSUE TITLE
[Question] Export QR with transparency (PNG or SVG Export)

### ISSUE THREAD

**Issue by ashniazi** [lara-zeus/qr#6]
Hi Lara Zeus,

Just wondering if there's support to export a QR code without a background color (alpha channel / transparency as a png or possibly svg) in this package?

Thank you for your work!

**Comment by atmonshi** [comment]
hey, I just checked the underline package, and it dose support alpha.
I'll add support for it later today, with the support for svg, and let you know :)

**Comment by atmonshi** [comment]
hey, the transparent background is done now
https://github.com/lara-zeus/qr/releases/tag/1.1.1

but downloading as an svg was not easy, still looking for a better solution.

**Comment by ashniazi** [comment]
@atmonshi wow you're fast! Thank you sir! I'm planning on adding it to my app in a week - if i find anything of value for svg export I'll ping back!

**Comment by atmonshi** [comment]
@ashniazi thanks :)
I actually already added the export to svg :)

<img width="424" alt="Screenshot 2024-01-12 at 12 34 26 PM" src="https://github.com/lara-zeus/qr/assets/1952412/cefe7f61-aae8-4f05-83c0-b84a4a5c533f">

if you have and feedback i am here to help :)
